# Generated by Django 4.1.4 on 2023-03-09 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='rasm')),
            ],
            options={
                'verbose_name': 'Test nomi ',
                'verbose_name_plural': 'Test nomlari ',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('javob1', models.CharField(max_length=200)),
                ('javob2', models.CharField(max_length=200)),
                ('javob3', models.CharField(max_length=500)),
                ('tugri_javob', models.CharField(max_length=500)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fanlar')),
            ],
            options={
                'verbose_name': 'Test ',
                'verbose_name_plural': 'Testlar ',
            },
        ),
    ]
